const JWT="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJhOTgxNjk2MS1lMzgzLTQxZTMtOTA0NS1iZmZjZTkxNWI4MGUiLCJlbWFpbCI6InNhbWVlcmdvZWxtYWlsQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiI3N2Q3NmI4NWRmYTQ4NGU1YjlkZSIsInNjb3BlZEtleVNlY3JldCI6ImU5ZjNmNGMxMDMyZTk3NDUzY2E0NzYyZjNkMmNiZGE2MzY5MzIyZTZkNDhlYmVlMTQwMjIyNGI3OGVmOTY4MTQiLCJleHAiOjE3NTcwNzY1MjV9.S6VX64l6L2pZI3ZWIz6wM2F6fv2fUNrVgwH6sPRABOY";
const Pinata_gateway_key="qaqgZzaeCuzn_eu5kQrAkty_mIjwW--t0nTBbxH0HUUUjlsmFH5ja-2nXZp5MKE4"
const pinata = new PinataSDK({
    pinataJwt: JWT,
    pinataGateway: Pinata_gateway_key,
});

async function main() {
  try {
    const data = await pinata.gateways.get("bafkreihj5w5cpsbfzwt5ydmhn4auaxkt3wwy3kdxcvaydqqbbo3hzx77c4");
    console.log(data)
  } catch (error) {
    console.log(error);
  }
}

/*
bafkreihj5w5cpsbfzwt5ydmhn4auaxkt3wwy3kdxcvaydqqbbo3hzx77c4
 */